DROP DATABASE IF EXISTS employees_db; 
CREATE DATABASE employees_db;

CREATE TABLE departments(
id: INT PRIMARY KEY AUTO_INCREMENT
name: VARCHAR(30) NOT NULL
);
CREATE TABLE role(
id: INT PRIMARY KEY AUTO_INCREMENT 
title: VARCHAR(30) NOT NULL 
salary: DECIMAL (10, 2) NOT NULL 
department_id: INT
);

CREATE TABLE employee(
id: INT PRIMARY KEY
first_name: VARCHAR(30) NOT NULL
last_name: VARCHAR(30) NOT NULL 
role_id: INT
manager_id: INT
);